*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZGCTS_TOGGLE_BADU01.
                    "TABLEFRAME_ZGCTS_TOGGLE_BAD
INCLUDE LZGCTS_TOGGLE_BADU02.
                    "TABLEPROC_ZGCTS_TOGGLE_BAD